# yazi.toml
[mgr]
show_hidden = true
ratio = [2,3,4]
sort_reverse = true
mouse_events = ["click", "scroll", "touch", "move", "drag"]

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "linux" },
]
play = [
	{ run = 'mpv "$@"', block = true, for = "linux" },
]
open = [
	{ run = 'nsxiv "$@"', block = true, for = "image/jpeg" },
	{ run = 'nsxiv "$@"', block = true, for = "image/png" },
	{ run = 'nsxiv "$@"', block = true, for = "image/gif" },
	{ run = 'nsxiv "$@"', block = true, for = "image/webp" },
	{ run = 'nsxiv "$@"', block = true, for = "image/bmp" },
	{ run = 'nsxiv "$@"', block = true, for = "image/tiff" },
]
