# yazi.toml
[mgr]
show_hidden = true
ratio = [2,3,4]
# sort_by = "created"
sort_reverse = true
mouse_events = ["click","scroll","touch","move","drag"]

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "linux" },
]
play = [
	{ run = 'mpv "$@"', block = true, for = "linux" },
]

[plugin.custom-actions]
block = false  # Run commands in a non-blocking shell by default
commands = [
    { name = "Open with nano", cmd = "/usr/bin/nano", block = true },
    { name = "Open with zathura", cmd = "zathura" },
]

[plugin.file-actions]
block = false  # Run commands in a non-blocking shell by default
